### PR TITLE
small modifications to pytorch notebooks

### PR DESCRIPTION
**Pull request by plooploops**

### CODE REVIEW

**Comment by plooploops** [comment]
Updated to account for small changes in DS VM for logins (docker / az cli / AKS usage).

**Comment by msalvaris** [comment]
Thanks @plooploops. 

Some of the issues you had seem to stem from python-dotenv not working properly. We have reported the [issue](https://github.com/theskumar/python-dotenv/issues/134). I will adjust the conda yaml file to install from master which doesn't have the issue. We have a requirement for doing things using .env files to avoid people inadvertently leaking information.

Diffing notebooks is kind of hard so may simply extract the pieces that are relevant from your PR and insert them. Is that ok or would you rather have me create a branch you can push to and I make my edits there?

**Comment by plooploops** [comment]
No worries.  If you want to extract the pieces that are relevant from the PR and insert them that's fine.

**Comment by msalvaris** [comment]
@plooploops Thanks for the PR. I have extracted the relevant parts and included them in #43 . Thanks :)

**Comment by plooploops** [comment]
@msalvaris Thank you for pulling in the relevant parts :)

**Pull request closed without merging**
